import { Bins } from "../components/bins.slint";
import { Time } from "../components/time.slint";
import { Api, Pages } from "../api.slint";
import { Button } from "std-widgets.slint";

export component HomePage {
    width: 100%;
    height: 100%;

    VerticalLayout {
        padding: 8px;
        alignment: space-between;

        HorizontalLayout {
            alignment: LayoutAlignment.space-between;

            Bins {
                is-yellow-bin: Api.is-yellow-bin;
                days-to-bin: Api.days-to-bin;
            }

            Time {
                time: Api.current-time;
                date: Api.current-date;
            }
        }

        HorizontalLayout {

            Button {
                text: "Settings";
                clicked => {
                    Api.current-page = Pages.settings;
                }
            }

            Text {
                text: "longitude: " + Api.coordinates.longitude;
            }

            Text {
                text: "latitude: " + Api.coordinates.latitude;
            }
        }
    }
}
