import { Button } from "std-widgets.slint";
import { Api, Pages } from "../api.slint";
import { Utils, AppFonts} from "../common.slint";
import { Bins } from "../components/bins.slint";
import { Time } from "../components/time.slint";
import { WeatherDaily } from "../components/weather_daily.slint";
import { WeatherCurrent } from "../components/weather_current.slint";
import { WeatherHourly } from "../components/weather_hourly.slint";

export component HomePage {
    width: 100%;
    height: 100%;

    VerticalLayout {
        padding: 8px;
        spacing: 8px;
        alignment: stretch;

        HorizontalLayout {
            alignment: LayoutAlignment.space-between;

            Bins {
                is-yellow-bin: Api.is-yellow-bin;
                days-to-bin: Api.days-to-bin;
            }

            Time {
                time: Api.current-time;
                date: Api.current-date;
            }
        }

        HorizontalLayout {
            vertical-stretch: 1;

            WeatherCurrent {
                current: Api.weather-current;
            }

            VerticalLayout {
                horizontal-stretch: 1;
                alignment: LayoutAlignment.stretch;
                spacing: 8px;

                WeatherHourly {
                    hourly: Api.weather-hourly;
                }

                WeatherDaily {
                    vertical-stretch: 2;
                    daily: Api.weather-daily;
                }
            }
        }

        HorizontalLayout {
            alignment: space-between;

            Button {
                text: "Settings";
                clicked => {
                    Api.current-page = Pages.settings;
                }
            }

            Text {
                text: "Updated: " + Utils.add-number-prefix(Api.weather-updated-at.hour) + ":" + Utils.add-number-prefix(Api.weather-updated-at.minute) + ":" + Utils.add-number-prefix(Api.weather-updated-at.second);
            }
        }
    }
}
