import { LineEdit, Button } from "std-widgets.slint";
import { Api, Pages, Coordinates } from "../api.slint";

export component SettingsPage {
    width: 100%;
    height: 100%;

    VerticalLayout {
        padding: 16px;

        alignment: LayoutAlignment.space-between;

        HorizontalLayout {
            spacing: 1rem;

            Text {
                text: "Lat:";
                vertical-alignment: center;
            }

            lat := LineEdit {
                input-type: decimal;
                height: 3rem;
                text: Api.coordinates.latitude;
            }

            Text {
                text: "Lon:";
                vertical-alignment: center;
            }

            lon := LineEdit {
                height: 3rem;
                input-type: decimal;
                text: Api.coordinates.longitude;
            }

            Button {
                height: 3rem;
                text: "Update location";

                clicked => {
                    Api.coordinates = {
                        latitude: lat.text.to-float(),
                        longitude: lon.text.to-float(),
                    };
                    Api.coordinates-updated(Api.coordinates);
                }
            }
        }

        Button {
            height: 3rem;
            text: "Home";
            clicked => {
                Api.current-page = Pages.home;
            }
        }
    }
}
