import { LineEdit, Button } from "std-widgets.slint";
import { Api, Pages, Coordinates } from "../api.slint";

export component SettingsPage {
    width: 100%;
    height: 100%;

    VerticalLayout {
        spacing: 1rem;

        lat := LineEdit {
            input-type: decimal;
            placeholder-text: "Lat";
        }

        lon := LineEdit {
            input-type: decimal;
            placeholder-text: "Lon";
        }

        Button {
            text: "Update location";

            clicked => {
                Api.coordinates = {
                    latitude: lat.text.to-float(),
                    longitude: lon.text.to-float(),
                };
                Api.coordinates-updated(Api.coordinates);
            }
        }

        Button {
            text: "Home";
            clicked => {
                Api.current-page = Pages.home;
            }
        }
    }
}
