// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT
import { Palette, Style } from "../common.slint";
import { Date, Time } from "std-widgets.slint";

export component Time {

    in property <Time> time;
    in property <Date> date;

    HorizontalLayout {
        alignment: center;
        spacing: 20px;
        VerticalLayout {
            alignment: center;
            Text {
                text: time.hour + ":" + time.minute + ":" + time.second;
                horizontal-alignment: center;
                vertical-alignment: center;
                color: Palette.info-foreground;
                font-size: Style.H1-font-size;
            }

            Text {
                text: date.day + "-" + date.month + "-" + date.year;
                horizontal-alignment: center;
                vertical-alignment: center;
                color: Palette.info-foreground;
                font-size: Style.H1-font-size;
            }
        }
    }
}
