import { Date, Time } from "std-widgets.slint";

export struct Coordinates  {
    longitude: float,
    latitude: float,
}

export global Api {
    in-out property <bool> is-yellow-bin:true;
    in-out property <int> days-to-bin:0;

    in-out property <Coordinates> coordinates;

    in-out property <Date> current-date: {
        year: 2025,
        month: 3,
        day: 18,
    };

    in-out property <Time> current-time: {
        hour: 15,
        minute: 12,
        second: 33,
    };
}
