import { Date, Time } from "std-widgets.slint";

export enum Pages { home, settings }

export struct Coordinates  {
    longitude: float,
    latitude: float,
}

export struct WeatherDaily {
    temperature_max: float,
    temperature_min: float,
    date: Date,
    precipitation_sum: float,
    precipitation_probability_max: int,
    weather_code: int,
    sunrise: Time,
    sunset: Time,
}

export global Api {
    in-out property <Pages> current-page: Pages.home;

    in-out property <bool> is-yellow-bin: true;
    in-out property <int> days-to-bin: 0;

    in-out property <[WeatherDaily]> weather-daily;

    in-out property <Coordinates> coordinates: {
        latitude: 0,
        latitude: 0,
    };
    callback coordinates-updated(Coordinates);

    in-out property <Date> current-date: {
        year: 2025,
        month: 3,
        day: 18,
    };

    in-out property <Time> current-time: {
        hour: 15,
        minute: 12,
        second: 33,
    };
}
