import { AboutSlint, VerticalBox, HorizontalBox } from "std-widgets.slint";
import { Api } from "./api.slint";
import { Time } from "components/time.slint";
import { Bins } from "components/bins.slint";

export {Api}


export component App inherits Window {
    width: 800px;
    height: 480px;

    VerticalLayout {
        padding: 8px;
        alignment: space-between;

        HorizontalLayout {
            alignment: LayoutAlignment.space-between;

            Bins {
                is-yellow-bin: Api.is-yellow-bin;
                days-to-bin: Api.days-to-bin;
            }

            Time {
                time: Api.current-time;
                date: Api.current-date;
            }
        }

        HorizontalLayout {

            Text {
                text:  "longitude: " +Api.coordinates.longitude;
            }
            Text {
                text:  "latitude: " +Api.coordinates.latitude;
            }
        }
    }
}
