import { AboutSlint, VerticalBox, HorizontalBox } from "std-widgets.slint";
import { Api } from "./api.slint";
import { Time } from "components/time.slint";
import { Bin } from "components/bin.slint";

export {Api}


export component App inherits Window {
    width: 800px;
    height: 480px;

    HorizontalLayout {

        HorizontalBox {

            Bin {
                color: red;
            }

            Bin {
                color: green;
            }

            if(Api.is-yellow-bin): Bin {
                color: yellow;
            }
        }

        Time {
            time: Api.current-time;
            date: Api.current-date;
        }
    }
}
