import { AboutSlint, VerticalBox, HorizontalBox } from "std-widgets.slint";
import { Api, Pages } from "./api.slint";
import { Time } from "components/time.slint";
import { Bins } from "components/bins.slint";
import { HomePage } from "./pages/home_page.slint";
import { SettingsPage } from "pages/settings_page.slint";

export {Api}


export component App inherits Window {
    width: 800px;
    height: 480px;

    if (Api.current-page == Pages.home): HomePage { }
    if (Api.current-page == Pages.settings): SettingsPage { }
}
